[tools]
node = "lts"
python = "latest"
go = "latest"
uv = "latest"

"npm:ctx7" = "latest"
"npm:@playwright/cli" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "java", "go"]
