[general]
import = [
  "~/.config/alacritty/themes/flexoki-light.toml",
  "~/.cache/dotfiles/alacritty-theme-active.toml",
]
live_config_reload = true

[font]
size = 14.0

[scrolling]
history = 10000

[window]
option_as_alt = "Both"
decorations = "Buttonless"
padding = { x = 2, y = 2 }

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "Enter", mods = "Shift", chars = "\u001B\r" },
  { key = "Space", mods = "Command|Shift", action = "ToggleViMode" },
  { key = "Y", mods = "Command|Shift", command = { program = "/bin/sh", args = ["-c", "$HOME/dotfiles/scripts/unwrap-clipboard.sh"] } },
  { key = "N", mods = "Command|Shift", chars = "\u001B[120~" },
  { key = "P", mods = "Command|Shift", chars = "\u001B[121~" },
  { key = "1", mods = "Command", chars = "\u001B[122~" },
  { key = "2", mods = "Command", chars = "\u001B[123~" },
  { key = "3", mods = "Command", chars = "\u001B[124~" },
  { key = "4", mods = "Command", chars = "\u001B[125~" },
  { key = "5", mods = "Command", chars = "\u001B[126~" },
  { key = "6", mods = "Command", chars = "\u001B[127~" },
  { key = "7", mods = "Command", chars = "\u001B[128~" },
  { key = "8", mods = "Command", chars = "\u001B[129~" },
  { key = "9", mods = "Command", chars = "\u001B[130~" },
  { key = "U", mods = "Command|Shift", chars = "\u001B[27;4;117~" },
  { key = "D", mods = "Command|Shift", chars = "\u001B[27;4;100~" },
  { key = "J", mods = "Command|Shift", chars = "\u001B[27;4;106~" },
  { key = "K", mods = "Command|Shift", chars = "\u001B[27;4;107~" },
]
