return {
  ["0"] = { action = "window_maximize" },
  ["1"] = { action = "window_left" },
  ["2"] = { action = "window_right" },
  ["3"] = { action = "window_two_thirds" },
  ["`"] = { action = "window_next_screen" },
  a = "Alacritty",
  c = "Calendar",
  f = "Finder",
  h = "Helium",
  m = "Mail",
  n = { action = "notification_center" },
  o = { action = "finder_in_alacritty" },
  p = "Preview",
  q = { action = "run_in_alacritty", command = "vi ~/box/notes.txt" },
  t = "TablePlus",
  s = "Sublime Text",
  w = "WeChat",
  z = "Firefox",
}
