return {
	-- Values can be an app name/bundle ID/path, or a table with an action.
	["1"] = { action = "window_left" },
	["2"] = { action = "window_right" },
	b = "Brave Browser",
	c = "Calendar",
	f = "Finder",
	g = "Ghostty",
	h = "Hammerspoon",
	i = "iPhone Mirroring",
	k = "kap",
	l = "Logseq",
	m = "Mail",
	n = { action = "notification_center" },
	s = "Sublime Text",
	t = "TablePlus",
	r = "Shottr",
	w = "WeChat",
	z = "System Settings",
}
