[mgr]
show_hidden = true
ratio = [0, 2, 3]

[plugin]
prepend_previewers = [
  { mime = "image/*", run = "viu" },
]

[opener]
play = [
  { run = 'if command -v mpv >/dev/null 2>&1; then mpv %s; else iina %s; fi', orphan = true, desc = "mpv", for = "unix" },
]
