#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/lib.sh"

LABEL="com.genkio.clipboard-bridge"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LISTEN_PORT=52527
VIEWER_PORT=52528
SSH_CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/ssh"
SSH_CONF="$SSH_CONF_DIR/clipboard-bridge.conf"

DRY_RUN=0
case "${1:-}" in
  --dry-run|-n) DRY_RUN=1 ;;
esac

if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "clipboard bridge agent is macOS only; skipping."
  exit 0
fi

machine_hosts() {
  command -v herdr >/dev/null 2>&1 || return 0
  local target host
  while IFS=$'\t' read -r _ _ target _; do
    host="${target#*://}"
    host="${host##*@}"
    host="${host%%:*}"
    [[ -n "$host" ]] && printf '%s\n' "$host"
  done < <(herdr machine list 2>/dev/null) | sort -u
}

HOSTS=()
while IFS= read -r host; do
  [[ -n "$host" ]] && HOSTS+=("$host")
done < <(machine_hosts)

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "  [dry-run] would reload $LABEL from $PLIST"
  echo "  [dry-run] would forward port $VIEWER_PORT from: ${HOSTS[*]:-no saved machines}"
  exit 0
fi

mkdir -p "$SSH_CONF_DIR"
{
  echo "# Generated by scripts/install-clipboard-bridge.sh; edits are overwritten."
  echo "# One block per saved Herdr machine, so copies there reach this clipboard."
  for host in "${HOSTS[@]:-}"; do
    [[ -n "$host" ]] || continue
    printf '\nHost %s\n  RemoteForward 127.0.0.1:%s 127.0.0.1:%s\n' \
      "$host" "$VIEWER_PORT" "$LISTEN_PORT"
  done
} >"$SSH_CONF"
chmod 600 "$SSH_CONF"

if [[ -r "$HOME/.ssh/config" ]] && ! grep -q 'dotfiles/ssh/\*\.conf' "$HOME/.ssh/config"; then
  warn "~/.ssh/config does not include $SSH_CONF_DIR/*.conf; remote copies stay remote."
fi

if [[ ! -e "$PLIST" ]]; then
  mkdir -p "$HOME/Library/LaunchAgents"
  stow -d "$REPO_ROOT" -t "$HOME" launchd
fi

DOMAIN="gui/$(id -u)"
launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true

if launchctl bootstrap "$DOMAIN" "$PLIST" 2>/dev/null; then
  echo "clipboard bridge listening on 127.0.0.1:$LISTEN_PORT for: ${HOSTS[*]:-no saved machines}"
else
  warn "could not load $LABEL; load it with 'launchctl bootstrap $DOMAIN $PLIST'."
fi
