#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/lib.sh"

LABEL="com.genkio.taildrop"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG="$HOME/Library/Logs/$LABEL.log"
DEST="${TAILDROP_DIR:-$HOME/Downloads}"

DRY_RUN=0
case "${1:-}" in
  --dry-run|-n) DRY_RUN=1 ;;
esac

if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "taildrop agent is macOS only; skipping."
  exit 0
fi

tailscale_bin() {
  local prefix
  if prefix="$(brew --prefix 2>/dev/null)" && [[ -x "$prefix/opt/tailscale/bin/tailscale" ]]; then
    printf '%s' "$prefix/opt/tailscale/bin/tailscale"
  elif command -v tailscale >/dev/null 2>&1; then
    command -v tailscale
  fi
}

TS="$(tailscale_bin)"
if [[ -z "$TS" ]]; then
  warn "tailscale is not installed; run 'make tailscale' first."
  exit 0
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "  [dry-run] would reload $LABEL, receiving taildrop files into $DEST"
  exit 0
fi

mkdir -p "$DEST" "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"

cat >"$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/install-taildrop.sh; edits are overwritten. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$TS</string>
    <string>file</string>
    <string>get</string>
    <string>--loop</string>
    <string>--verbose</string>
    <string>--conflict=rename</string>
    <string>$DEST</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>30</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>$LOG</string>
  <key>StandardErrorPath</key>
  <string>$LOG</string>
</dict>
</plist>
PLIST_EOF

DOMAIN="gui/$(id -u)"
launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true

if launchctl bootstrap "$DOMAIN" "$PLIST" 2>/dev/null; then
  echo "taildrop receiver running; files from the tailnet land in $DEST"
else
  warn "could not load $LABEL; load it with 'launchctl bootstrap $DOMAIN $PLIST'."
fi
