#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/lib.sh"

LABEL="com.genkio.clipboard-bridge"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LISTEN_PORT=52527
VIEWER_BASE=52528
VIEWER_SLOTS=8
SSH_CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/ssh"
SSH_CONF="$SSH_CONF_DIR/clipboard-bridge.conf"

DRY_RUN=0
case "${1:-}" in
  --dry-run|-n) DRY_RUN=1 ;;
esac

if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "clipboard bridge agent is macOS only; skipping."
  exit 0
fi

herdr_bin() {
  if [[ -n "${HERDR_BIN_PATH:-}" && -x "$HERDR_BIN_PATH" ]]; then
    printf '%s' "$HERDR_BIN_PATH"
  elif command -v herdr >/dev/null 2>&1; then
    command -v herdr
  elif [[ -x "$HOME/.local/bin/herdr" ]]; then
    printf '%s' "$HOME/.local/bin/herdr"
  fi
}

machine_hosts() {
  local bin="$1" target host
  while IFS=$'\t' read -r _ _ target _; do
    host="${target#*://}"
    host="${host##*@}"
    host="${host%%:*}"
    [[ -n "$host" ]] && printf '%s\n' "$host"
  done < <("$bin" machine list 2>/dev/null) | sort -u
}

HOSTS=()
HERDR="$(herdr_bin)"
if [[ -n "$HERDR" ]]; then
  while IFS= read -r host; do
    [[ -n "$host" ]] && HOSTS+=("$host")
  done < <(machine_hosts "$HERDR")
fi

WRITE_CONF=1
if [[ ${#HOSTS[@]} -eq 0 ]]; then
  WRITE_CONF=0
  warn "no herdr machines found; leaving $SSH_CONF as is."
fi

SELF="$(hostname -s)"

viewer_port() {
  local i=0 name
  while IFS= read -r name; do
    [[ "$name" == "$SELF" ]] && break
    i=$((i + 1))
  done < <(printf '%s\n' "$SELF" "${HOSTS[@]:-}" | grep -v '^$' | sort -u)
  printf '%s' "$((VIEWER_BASE + i % VIEWER_SLOTS))"
}
VIEWER_PORT="$(viewer_port)"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "  [dry-run] would reload $LABEL from $PLIST"
  echo "  [dry-run] would forward port $VIEWER_PORT ($SELF's slot) from: ${HOSTS[*]:-no saved machines}"
  exit 0
fi

if [[ "$WRITE_CONF" -eq 1 ]]; then
  mkdir -p "$SSH_CONF_DIR"
  {
    echo "# Generated by scripts/install-clipboard-bridge.sh; edits are overwritten."
    echo "# One block per saved Herdr machine, so copies there reach this clipboard."
    for host in "${HOSTS[@]}"; do
      printf '\nHost %s\n  RemoteForward 127.0.0.1:%s 127.0.0.1:%s\n' \
        "$host" "$VIEWER_PORT" "$LISTEN_PORT"
    done
  } >"$SSH_CONF"
  chmod 600 "$SSH_CONF"
fi

if [[ -r "$HOME/.ssh/config" ]] && ! grep -q 'dotfiles/ssh/\*\.conf' "$HOME/.ssh/config"; then
  warn "~/.ssh/config does not include $SSH_CONF_DIR/*.conf; remote copies stay remote."
fi

if [[ ! -e "$PLIST" ]]; then
  mkdir -p "$HOME/Library/LaunchAgents"
  stow -d "$REPO_ROOT" -t "$HOME" launchd
fi

DOMAIN="gui/$(id -u)"
launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true

if launchctl bootstrap "$DOMAIN" "$PLIST" 2>/dev/null; then
  echo "clipboard bridge listening on 127.0.0.1:$LISTEN_PORT, slot $VIEWER_PORT on: ${HOSTS[*]:-no saved machines}"
else
  warn "could not load $LABEL; load it with 'launchctl bootstrap $DOMAIN $PLIST'."
fi
