#!/usr/bin/env bash
# Usage: install-ccr-web.sh [--serve|--funnel|--off] [--dry-run]
#   --serve   reachable from devices on the tailnet only
#   --funnel  reachable from the public internet, guarded by the token only
#   --off     remove the Tailscale mapping, keep the local agent
# Mounted at /ccr on port 443 so other services can share the host.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/lib.sh"

LABEL="com.genkio.ccr-web"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG="$HOME/Library/Logs/$LABEL.log"
# Clear of the clipboard bridge, which takes 52527-52535 (see install-clipboard-bridge.sh).
PORT=52540
ROUTE=/ccr
TOKEN_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles"
TOKEN_FILE="$TOKEN_DIR/ccr-web.token"

DRY_RUN=0
MODE=""
for a in "$@"; do
  case "$a" in
    --dry-run|-n) DRY_RUN=1 ;;
    --serve) MODE=serve ;;
    --funnel) MODE=funnel ;;
    --off) MODE=off ;;
    *) err "unknown option: $a"; exit 1 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "ccr-web agent is macOS only; skipping."
  exit 0
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "  [dry-run] would reload $LABEL on 127.0.0.1:$PORT${MODE:+ and set tailscale $MODE}"
  exit 0
fi

if [[ -n "$MODE" ]] && ! command -v tailscale >/dev/null 2>&1; then
  warn "tailscale is not installed; run 'make tailscale' first."
  exit 1
fi

DOMAIN="gui/$(id -u)"

# Prints serve or funnel when the route points at this agent, else nothing.
route_mode() {
  tailscale serve status --json 2>/dev/null | /usr/bin/python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for hp, web in d.get("Web", {}).items():
    if hp.endswith(":443") and web.get("Handlers", {}).get(sys.argv[1], {}).get("Proxy", "").endswith(":" + sys.argv[2]):
        print("funnel" if d.get("AllowFunnel", {}).get(hp) else "serve")
' "$ROUTE" "$PORT"
}

print_url() {
  local host
  host="$(tailscale status --json | /usr/bin/python3 -c 'import json, sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')"
  echo "  url:   https://$host$ROUTE/"
  echo "  token: $(cat "$TOKEN_FILE")"
  echo "  link:  https://$host$ROUTE/#t=$(cat "$TOKEN_FILE")  (opens with the token saved)"
}

if [[ "$MODE" == serve || "$MODE" == funnel ]] && [[ -s "$TOKEN_FILE" ]] &&
  launchctl print "$DOMAIN/$LABEL" 2>/dev/null | grep -q 'state = running' &&
  [[ "$(route_mode)" == "$MODE" ]]; then
  echo "ccr-web already running (tailscale $MODE)"
  print_url
  exit 0
fi

mkdir -p "$TOKEN_DIR" "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"
if [[ ! -s "$TOKEN_FILE" ]]; then
  (umask 077; openssl rand -hex 24 >"$TOKEN_FILE")
fi
chmod 600 "$TOKEN_FILE"

cat >"$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/install-ccr-web.sh; edits are overwritten. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/python3</string>
    <string>$SCRIPT_DIR/ccr-web</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$HOME/.local/bin:$HOME/.local/share/mise/shims:/opt/homebrew/bin:/usr/bin:/bin</string>
    <key>CCR_WEB_PORT</key>
    <string>$PORT</string>
    <key>CCR_WEB_TOKEN_FILE</key>
    <string>$TOKEN_FILE</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>30</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>$LOG</string>
  <key>StandardErrorPath</key>
  <string>$LOG</string>
</dict>
</plist>
PLIST_EOF

launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true
# bootout returns before the job is gone, and bootstrap fails until it is.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1 || break
  sleep 0.5
done
if ! launchctl bootstrap "$DOMAIN" "$PLIST" 2>/dev/null; then
  warn "could not load $LABEL; load it with 'launchctl bootstrap $DOMAIN $PLIST'."
  exit 1
fi
[[ -n "$MODE" ]] || { echo "ccr-web listening on 127.0.0.1:$PORT"; exit 0; }

# Funnel is per port, not per path: anything else mounted on 443 is public
# too, so keep tailnet-only services on another port.
tailscale serve --https=443 --set-path "$ROUTE" off >/dev/null 2>&1 || true
case "$MODE" in
  off) echo "tailscale mapping removed"; exit 0 ;;
  serve) tailscale serve --bg --https=443 --set-path "$ROUTE" "http://127.0.0.1:$PORT" >/dev/null ;;
  funnel) tailscale funnel --bg --https=443 --set-path "$ROUTE" "http://127.0.0.1:$PORT" >/dev/null ;;
esac

echo "ccr-web started (tailscale $MODE)"
print_url
